"use server";

import { revalidatePath } from "next/cache";
import { requireSession } from "@/lib/session";
import {
  presignChatAttachment,
  confirmChatAttachment,
  getChatAttachmentUrl,
  listMyChats,
  editChatMessage,
  forwardChatMessage,
  getChatRoomById,
  hideChatMessage,
  listRoomMedia,
  markChatDelivered,
  searchChatMessages,
  setChatArchived,
  setChatMuted,
  setChatPinned,
  toggleChatReaction,
  listChatMessages,
  sendChatMessage,
  markChatRead,
  deleteChatMessage,
  reportChatMessage,
  pinChatMessage,
  muteChatMember,
  setChatModerator,
  banChatMember,
  updateChatRoom,
  type ChatMessage,
  type ChatMessagePage,
  type ChatRoom,
  type ChatAttachment,
  type AttachmentTicket,
  type MyChat
} from "@/lib/chat-api";

/// Server actions are the only path from the browser to the chat API.
///
/// The session token lives in an httpOnly cookie and stays there: every REST call is made here,
/// server-side. The one place the token is handed to client JS is `/api/realtime-token`, and that
/// copy is used solely to open the SignalR connection (D-109) — never for REST.

export async function fetchMyChatsAction(archived = false): Promise<MyChat[]> {
  const session = await requireSession();
  return listMyChats(session.accessToken, archived);
}

/// Keyed on the ROOM id (D-292), so a direct room resolves through the same path an event room does.
export async function fetchRoomAction(roomId: string): Promise<ChatRoom> {
  const session = await requireSession();
  return getChatRoomById(session.accessToken, roomId);
}

/// D-293 — edit and delete-for-me. Both go through a server action like every other chat call, so
/// the session token never reaches client JS.
export async function editMessageAction(messageId: string, body: string): Promise<ChatMessage> {
  const session = await requireSession();
  return editChatMessage(session.accessToken, messageId, body);
}

export async function hideMessageAction(messageId: string): Promise<void> {
  const session = await requireSession();
  await hideChatMessage(session.accessToken, messageId);
}

// ── D-295 ─────────────────────────────────────────────────────────────────────
// Server actions like every other chat call, so the session token never reaches client JS.

export async function toggleReactionAction(messageId: string, emoji: string) {
  const session = await requireSession();
  return toggleChatReaction(session.accessToken, messageId, emoji);
}

export async function searchMessagesAction(q: string, roomId?: string) {
  const session = await requireSession();
  return searchChatMessages(session.accessToken, q, { roomId });
}

export async function markDeliveredAction(roomId: string, messageId: string) {
  const session = await requireSession();
  await markChatDelivered(session.accessToken, roomId, messageId);
}

export async function forwardMessageAction(
  messageId: string,
  targetRoomId: string,
  clientMessageId?: string
) {
  const session = await requireSession();
  return forwardChatMessage(session.accessToken, messageId, targetRoomId, clientMessageId);
}

export async function setPinnedAction(roomId: string, pinned: boolean) {
  const session = await requireSession();
  await setChatPinned(session.accessToken, roomId, pinned);
  revalidatePath("/chats");
}

export async function setMutedAction(roomId: string, until: string | null) {
  const session = await requireSession();
  await setChatMuted(session.accessToken, roomId, until);
  revalidatePath("/chats");
}

/// D-306 — files an EVENT room away, or restores it. DMs keep their own action in `account-actions`
/// because they answer on a different route; both end at the same `SetArchivedAsync`.
export async function setChatArchivedAction(roomId: string, archived: boolean) {
  const session = await requireSession();
  await setChatArchived(session.accessToken, roomId, archived);
  revalidatePath("/chats");
}

export async function roomMediaAction(roomId: string) {
  const session = await requireSession();
  return listRoomMedia(session.accessToken, roomId);
}

export async function fetchMessagesAction(
  roomId: string,
  opts: { before?: string; after?: string; limit?: number } = {}
): Promise<ChatMessagePage> {
  const session = await requireSession();
  return listChatMessages(session.accessToken, roomId, opts);
}

/// `clientMessageId` is generated by the caller before the first attempt, which is what makes a
/// retry idempotent instead of duplicating.
export async function sendMessageAction(
  roomId: string,
  body: string,
  clientMessageId: string,
  replyToMessageId?: string,
  attachmentIds?: string[]
): Promise<ChatMessage> {
  const session = await requireSession();
  return sendChatMessage(session.accessToken, roomId, {
    body,
    clientMessageId,
    replyToMessageId,
    attachmentIds
  });
}

// ── Attachments ───────────────────────────────────────────────────────────────────────────
// Presign and confirm run here so the session token never reaches the browser. The PUT in between
// deliberately does NOT: it goes browser-direct to the presigned URL, because that URL carries its
// own signature and must not receive cookies, an Authorization header, or any interceptor.

export async function presignAttachmentAction(
  roomId: string,
  fileName: string,
  contentType: string,
  sizeBytes: number
): Promise<AttachmentTicket> {
  const session = await requireSession();
  return presignChatAttachment(session.accessToken, roomId, { fileName, contentType, sizeBytes });
}

export async function confirmAttachmentAction(
  roomId: string,
  storageKey: string
): Promise<ChatAttachment> {
  const session = await requireSession();
  return confirmChatAttachment(session.accessToken, roomId, storageKey);
}

export async function attachmentUrlAction(attachmentId: string): Promise<string> {
  const session = await requireSession();
  return getChatAttachmentUrl(session.accessToken, attachmentId);
}

export async function markReadAction(roomId: string, lastReadMessageId: string): Promise<void> {
  const session = await requireSession();
  await markChatRead(session.accessToken, roomId, lastReadMessageId);
}

export async function deleteMessageAction(messageId: string): Promise<void> {
  const session = await requireSession();
  await deleteChatMessage(session.accessToken, messageId);
}

export async function reportMessageAction(messageId: string, reason: string): Promise<void> {
  const session = await requireSession();
  await reportChatMessage(session.accessToken, messageId, reason);
}

// ── Host moderation. The backend re-checks host role on every one of these. ──────────────────

export async function pinMessageAction(
  messageId: string,
  pin: boolean,
  durationHours?: number
): Promise<void> {
  const session = await requireSession();
  await pinChatMessage(session.accessToken, messageId, pin, durationHours);
}

/// D-301 — Host-only; the server refuses a Moderator attempting either direction.
export async function setModeratorAction(
  roomId: string,
  userId: string,
  moderator: boolean
): Promise<void> {
  const session = await requireSession();
  await setChatModerator(session.accessToken, roomId, userId, moderator);
}

export async function muteMemberAction(
  roomId: string,
  userId: string,
  minutes: number
): Promise<void> {
  const session = await requireSession();
  await muteChatMember(session.accessToken, roomId, userId, minutes);
}

export async function banMemberAction(roomId: string, userId: string): Promise<void> {
  const session = await requireSession();
  await banChatMember(session.accessToken, roomId, userId);
}

export async function updateRoomAction(
  roomId: string,
  input: { postPolicy?: string; status?: string }
): Promise<void> {
  const session = await requireSession();
  await updateChatRoom(session.accessToken, roomId, input);
}
