using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Kurx.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class MigrateCanonicalTaxonomy : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // D-266 M3 Step 6 Phase 4. GENERATED by scratchpad/gen_phase4.py from TaxonomyAliasMap — do not
            // hand-edit; the map is the source of truth and 15 Phase 2 tests verify it.
            //
            // Verified on a clean database: both installation paths converge on 113 rows / 104 logical
            // types / the same 9 approved navigation duplicates, with 0 events on retired types and 0
            // orphaned foreign keys.
            migrationBuilder.Sql(@"-- D-266 M3 Step 6 Phase 4. GENERATED from TaxonomyAliasMap by gen_phase4.py. Do not hand-edit.
--
-- Shape: RENAME IN PLACE, not insert-then-retire. EventCategory.Slug is documented as
-- permanently immutable after creation and explicitly unchanged on rename, so renaming a row
-- touches Name only. That is what makes this collision-free: an insert-based migration tried to
-- create 'Sports Tournament' in the Public branch with the prefixed slug
-- 'public-sports-tournament', which the legacy type 'Public Sports Tournament' already owned.
-- Renaming also preserves the row id, so events keep resolving with no remap at all.

-- 1) Attributes FIRST, while rows still carry their legacy names. After the rename every
--    cricket event reads 'Sports Tournament' and the sport is unrecoverable.
UPDATE events e SET ""Sport"" = 'Cricket'
FROM event_categories c
WHERE e.""TypeId"" = c.""Id"" AND c.""Name"" = 'Cricket Tournament' AND e.""Sport"" IS NULL;
UPDATE events e SET ""Sport"" = 'Football'
FROM event_categories c
WHERE e.""TypeId"" = c.""Id"" AND c.""Name"" = 'Football Tournament' AND e.""Sport"" IS NULL;
UPDATE events e SET ""Sport"" = 'Basketball'
FROM event_categories c
WHERE e.""TypeId"" = c.""Id"" AND c.""Name"" = 'Basketball Tournament' AND e.""Sport"" IS NULL;
UPDATE events e SET ""Sport"" = 'Volleyball'
FROM event_categories c
WHERE e.""TypeId"" = c.""Id"" AND c.""Name"" = 'Volleyball Tournament' AND e.""Sport"" IS NULL;
UPDATE events e SET ""Sport"" = 'Badminton'
FROM event_categories c
WHERE e.""TypeId"" = c.""Id"" AND c.""Name"" = 'Badminton Tournament' AND e.""Sport"" IS NULL;
UPDATE events e SET ""Sport"" = 'Chess'
FROM event_categories c
WHERE e.""TypeId"" = c.""Id"" AND c.""Name"" = 'Chess Tournament' AND e.""Sport"" IS NULL;
UPDATE events e SET ""Sport"" = 'Athletics'
FROM event_categories c
WHERE e.""TypeId"" = c.""Id"" AND c.""Name"" = 'Athletics Meet' AND e.""Sport"" IS NULL;
UPDATE events e SET ""Sport"" = 'General'
FROM event_categories c
WHERE e.""TypeId"" = c.""Id"" AND c.""Name"" = 'Public Sports Tournament' AND e.""Sport"" IS NULL;
UPDATE events e SET ""Discipline"" = 'Art'
FROM event_categories c
WHERE e.""TypeId"" = c.""Id"" AND c.""Name"" = 'Art Competition' AND e.""Discipline"" IS NULL;
UPDATE events e SET ""Discipline"" = 'Photography'
FROM event_categories c
WHERE e.""TypeId"" = c.""Id"" AND c.""Name"" = 'Photography Competition' AND e.""Discipline"" IS NULL;
UPDATE events e SET ""Discipline"" = 'Film'
FROM event_categories c
WHERE e.""TypeId"" = c.""Id"" AND c.""Name"" = 'Film Competition' AND e.""Discipline"" IS NULL;
UPDATE events e SET ""Discipline"" = 'Writing'
FROM event_categories c
WHERE e.""TypeId"" = c.""Id"" AND c.""Name"" = 'Writing Competition' AND e.""Discipline"" IS NULL;
UPDATE events e SET ""Discipline"" = 'Design'
FROM event_categories c
WHERE e.""TypeId"" = c.""Id"" AND c.""Name"" = 'Design Competition' AND e.""Discipline"" IS NULL;
UPDATE events e SET ""Discipline"" = 'Music'
FROM event_categories c
WHERE e.""TypeId"" = c.""Id"" AND c.""Name"" = 'Music Competition' AND e.""Discipline"" IS NULL;
UPDATE events e SET ""Discipline"" = 'Dance'
FROM event_categories c
WHERE e.""TypeId"" = c.""Id"" AND c.""Name"" = 'Dance Competition' AND e.""Discipline"" IS NULL;
UPDATE events e SET ""Discipline"" = 'Talent'
FROM event_categories c
WHERE e.""TypeId"" = c.""Id"" AND c.""Name"" = 'Talent Competition' AND e.""Discipline"" IS NULL;
UPDATE events e SET ""Discipline"" = 'Fashion'
FROM event_categories c
WHERE e.""TypeId"" = c.""Id"" AND c.""Name"" = 'Fashion Competition' AND e.""Discipline"" IS NULL;
UPDATE events e SET ""Subject"" = 'Art'
FROM event_categories c
WHERE e.""TypeId"" = c.""Id"" AND c.""Name"" = 'Art Exhibition' AND e.""Subject"" IS NULL;
UPDATE events e SET ""Subject"" = 'Photography'
FROM event_categories c
WHERE e.""TypeId"" = c.""Id"" AND c.""Name"" = 'Photography Exhibition' AND e.""Subject"" IS NULL;
UPDATE events e SET ""VenueType"" = 'Destination'
FROM event_categories c
WHERE e.""TypeId"" = c.""Id"" AND c.""Name"" = 'Destination Wedding' AND e.""VenueType"" IS NULL;

-- 2) Rename in place — one legacy row per parent becomes the canonical type. The NOT EXISTS
--    guard makes this idempotent and stops a second legacy type in the same branch from
--    creating a duplicate: it falls through to step 3 instead.
UPDATE event_categories src SET ""Name"" = 'Campus Recruitment', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Placement Drive'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Campus Recruitment' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Internship Recruitment', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Internship Drive'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Internship Recruitment' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Site Visit', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Industrial Visit'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Site Visit' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Welcome Event', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Freshers Party'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Welcome Event' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Farewell Event', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Farewell Party'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Farewell Event' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Annual Celebration', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Annual Day'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Annual Celebration' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Campus Fest', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'College Fest'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Campus Fest' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Blood Drive', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Blood Donation Camp'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Blood Drive' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Health Screening', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Health Camp'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Health Screening' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Tree Planting', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Tree Plantation Drive'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Tree Planting' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Industry Talk', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Industry Interaction Session'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Industry Talk' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Career Fair', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Job Fair'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Career Fair' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Trade Show', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Industry Expo'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Trade Show' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Volunteer Event', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Community Service Event'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Volunteer Event' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Club Event', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Society Event'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Club Event' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Club Event', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Student Chapter Event'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Club Event' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Running Event', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Marathon'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Running Event' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Pre-Wedding Celebration', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Bachelor Party'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Pre-Wedding Celebration' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Pre-Wedding Celebration', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Bachelorette Party'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Pre-Wedding Celebration' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Private Ceremony', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Pooja Ceremony'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Private Ceremony' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Private Ceremony', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Religious Ceremony'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Private Ceremony' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Private Ceremony', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Prayer Meeting'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Private Ceremony' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Private Ceremony', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Festival Celebration'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Private Ceremony' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Private Ceremony', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Religious Gathering'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Private Ceremony' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Private Ceremony', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Traditional Family Function'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Private Ceremony' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Private Ceremony', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Coming-of-Age Ceremony'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Private Ceremony' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Private Ceremony', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Memorial Service'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Private Ceremony' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Private Celebration', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Gender Reveal Party'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Private Celebration' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Private Celebration', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Sleepover Party'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Private Celebration' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Networking Event', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Investor Meet'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Networking Event' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Sports Tournament', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Cricket Tournament'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Sports Tournament' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Sports Tournament', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Football Tournament'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Sports Tournament' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Sports Tournament', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Basketball Tournament'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Sports Tournament' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Sports Tournament', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Volleyball Tournament'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Sports Tournament' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Sports Tournament', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Badminton Tournament'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Sports Tournament' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Sports Tournament', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Chess Tournament'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Sports Tournament' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Sports Tournament', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Athletics Meet'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Sports Tournament' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Sports Tournament', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Public Sports Tournament'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Sports Tournament' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Creative Competition', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Art Competition'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Creative Competition' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Creative Competition', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Photography Competition'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Creative Competition' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Creative Competition', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Film Competition'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Creative Competition' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Creative Competition', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Writing Competition'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Creative Competition' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Creative Competition', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Design Competition'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Creative Competition' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Performance Competition', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Music Competition'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Performance Competition' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Performance Competition', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Dance Competition'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Performance Competition' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Performance Competition', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Talent Competition'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Performance Competition' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Performance Competition', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Fashion Competition'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Performance Competition' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Exhibition', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Art Exhibition'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Exhibition' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Exhibition', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Photography Exhibition'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Exhibition' AND d.""ParentId"" = src.""ParentId"");
UPDATE event_categories src SET ""Name"" = 'Wedding', ""UpdatedAt"" = now(), ""Version"" = src.""Version"" + 1
WHERE src.""Level"" = 'Type' AND src.""Name"" = 'Destination Wedding'
  AND NOT EXISTS (SELECT 1 FROM event_categories d
                  WHERE d.""Level"" = 'Type' AND d.""Name"" = 'Wedding' AND d.""ParentId"" = src.""ParentId"");

-- 3) Many-to-one merges: any legacy row still standing has a canonical sibling in its branch.
--    Move its events onto that sibling, then retire it.
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Placement Drive'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Campus Recruitment' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Internship Drive'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Internship Recruitment' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Industrial Visit'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Site Visit' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Freshers Party'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Welcome Event' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Farewell Party'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Farewell Event' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Annual Day'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Annual Celebration' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'College Fest'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Campus Fest' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Blood Donation Camp'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Blood Drive' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Health Camp'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Health Screening' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Tree Plantation Drive'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Tree Planting' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Industry Interaction Session'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Industry Talk' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Job Fair'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Career Fair' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Industry Expo'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Trade Show' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Community Service Event'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Volunteer Event' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Society Event'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Club Event' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Student Chapter Event'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Club Event' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Marathon'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Running Event' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Bachelor Party'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Pre-Wedding Celebration' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Bachelorette Party'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Pre-Wedding Celebration' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Pooja Ceremony'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Private Ceremony' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Religious Ceremony'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Private Ceremony' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Prayer Meeting'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Private Ceremony' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Festival Celebration'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Private Ceremony' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Religious Gathering'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Private Ceremony' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Traditional Family Function'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Private Ceremony' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Coming-of-Age Ceremony'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Private Ceremony' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Memorial Service'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Private Ceremony' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Gender Reveal Party'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Private Celebration' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Sleepover Party'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Private Celebration' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Investor Meet'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Networking Event' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Cricket Tournament'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Sports Tournament' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Football Tournament'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Sports Tournament' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Basketball Tournament'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Sports Tournament' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Volleyball Tournament'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Sports Tournament' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Badminton Tournament'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Sports Tournament' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Chess Tournament'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Sports Tournament' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Athletics Meet'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Sports Tournament' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Public Sports Tournament'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Sports Tournament' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Art Competition'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Creative Competition' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Photography Competition'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Creative Competition' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Film Competition'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Creative Competition' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Writing Competition'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Creative Competition' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Design Competition'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Creative Competition' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Music Competition'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Performance Competition' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Dance Competition'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Performance Competition' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Talent Competition'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Performance Competition' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Fashion Competition'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Performance Competition' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Art Exhibition'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Exhibition' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Photography Exhibition'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Exhibition' AND dst.""ParentId"" = s.""ParentId"";
UPDATE events e SET ""TypeId"" = dst.""Id""
FROM event_categories s, event_categories dst
WHERE e.""TypeId"" = s.""Id"" AND s.""Level"" = 'Type' AND s.""Name"" = 'Destination Wedding'
  AND dst.""Level"" = 'Type' AND dst.""Name"" = 'Wedding' AND dst.""ParentId"" = s.""ParentId"";

-- 3b) The one approved CROSS-AUDIENCE merge (D11 section 3): Volunteer Event existed under both
--     Student and Public and is a single public-facing type. Not expressible as a name mapping
--     because both rows already carry the canonical name, so it is stated explicitly here.
--     Public owns it; the Student node is retired after its events move across.
WITH student_node AS (
  SELECT t.""Id"" FROM event_categories t
  JOIN event_categories cat ON cat.""Id"" = t.""ParentId""
  JOIN event_categories aud ON aud.""Id"" = cat.""ParentId""
  WHERE t.""Level"" = 'Type' AND t.""Name"" = 'Volunteer Event' AND aud.""Name"" = 'Student Events'),
public_node AS (
  SELECT t.""Id"" FROM event_categories t
  JOIN event_categories cat ON cat.""Id"" = t.""ParentId""
  JOIN event_categories aud ON aud.""Id"" = cat.""ParentId""
  WHERE t.""Level"" = 'Type' AND t.""Name"" = 'Volunteer Event' AND aud.""Name"" = 'Public Events')
UPDATE events e SET ""TypeId"" = (SELECT ""Id"" FROM public_node)
WHERE e.""TypeId"" = (SELECT ""Id"" FROM student_node) AND EXISTS (SELECT 1 FROM public_node);
UPDATE event_categories SET ""Status"" = 'Retired', ""IsVisible"" = false, ""UpdatedAt"" = now()
WHERE ""Id"" IN (
  SELECT t.""Id"" FROM event_categories t
  JOIN event_categories cat ON cat.""Id"" = t.""ParentId""
  JOIN event_categories aud ON aud.""Id"" = cat.""ParentId""
  WHERE t.""Level"" = 'Type' AND t.""Name"" = 'Volunteer Event' AND aud.""Name"" = 'Student Events');

-- 4) Retire what remains. NOT deleted: analytics, certificates and historical events may still
--    reference these ids. Retired keeps them resolvable and out of the Create Event picker.
UPDATE event_categories SET ""Status"" = 'Retired', ""IsVisible"" = false, ""UpdatedAt"" = now()
WHERE ""Level"" = 'Type' AND ""Name"" IN ('Placement Drive','Internship Drive','Industrial Visit','Freshers Party','Farewell Party','Annual Day','College Fest','Blood Donation Camp','Health Camp','Tree Plantation Drive','Industry Interaction Session','Job Fair','Industry Expo','Community Service Event','Society Event','Student Chapter Event','Marathon','Bachelor Party','Bachelorette Party','Pooja Ceremony','Religious Ceremony','Prayer Meeting','Festival Celebration','Religious Gathering','Traditional Family Function','Coming-of-Age Ceremony','Memorial Service','Gender Reveal Party','Sleepover Party','Investor Meet','Cricket Tournament','Football Tournament','Basketball Tournament','Volleyball Tournament','Badminton Tournament','Chess Tournament','Athletics Meet','Public Sports Tournament','Art Competition','Photography Competition','Film Competition','Writing Competition','Design Competition','Music Competition','Dance Competition','Talent Competition','Fashion Competition','Art Exhibition','Photography Exhibition','Destination Wedding');");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Intentionally empty. Reverting would have to re-split merged types and attribute conversions
            // back into 50 legacy types, and the information needed to do that (which Sports Tournament was
            // a Cricket Tournament) now lives in the attribute columns rather than the type — restoring the
            // old shape would mean inventing rows. Recovery is restore-from-backup.
            //
            // Nothing is lost by leaving it: the legacy nodes are Retired, not deleted, so historical
            // references still resolve.
        }
    }
}
