using System.Text.Json;

namespace Kurx.Tests;

/// <summary>A ratchet on response-schema coverage in the committed contract (<c>docs/api/openapi.json</c>,
/// D-259/D-246).
///
/// <para><b>Why a ratchet rather than a target.</b> Most endpoints answer with a hand-written anonymous
/// object (<c>Results.Ok(ToOrderJson(...))</c>), which Swashbuckle cannot infer a schema from — declaring
/// <c>.Produces&lt;T&gt;()</c> on one of those without first giving it a named DTO would publish a schema
/// that does not match the bytes on the wire. A contract that lies is worse than one that is silent: it is
/// exactly how <c>web/lib/api.ts</c> came to require an <c>order_id</c> the server never sent, which threw
/// on every parse and showed every buyer an empty My Tickets page (D-245).</para>
///
/// <para>So coverage is raised endpoint by endpoint as each gains a real response type, and this test only
/// forbids going backwards. Raise <see cref="Baseline"/> when you add schemas — never lower it.</para></summary>
public class OpenApiCoverageTests
{
    /// <summary>Operations with a declared 200/201 body schema. Raise as coverage improves.
    /// 44 → 64 (D-262): the Posts module shipped with every value-returning route annotated.
    ///
    /// <para>64 → 464, measured 2026-08-14 against the committed spec (464 of 535 operations). The gap was
    /// not a sudden gain — D-313 annotated the API wholesale — but this constant never moved, because
    /// <see cref="SpecPath"/> could not find the spec under the container recipe's <c>-p:ArtifactsPath</c>
    /// and the caller treats "not found" as "not generated yet" and returns. So the ratchet passed by
    /// skipping in the container, and passed trivially everywhere else against a floor 400 operations
    /// below reality — it would not have caught a drop from 464 to 65. Both halves are fixed: the lookup
    /// (via <see cref="RepoRoot"/>) and the floor.</para></summary>
    private const int Baseline = 464;

    // Resolved through RepoRoot, from this source file's compile-time path. The previous
    // AppContext.BaseDirectory walk could not survive the container recipe's `-p:ArtifactsPath`, which puts
    // the binary outside the repo mount — and because the caller below treats "not found" as "not generated
    // yet" and returns, this ratchet silently stopped ratcheting in exactly the runner CI and local
    // verification use. A coverage gate that skips itself is worse than one that fails.
    private static string SpecPath()
        => RepoRoot.PathTo("docs", "api", "openapi.json") is { } path && File.Exists(path) ? path : "";

    [Fact]
    public void Response_schema_coverage_never_regresses()
    {
        var path = SpecPath();
        // The spec is generated by scripts/generate-openapi.sh against a running API. A developer who has
        // not generated it yet should not get a red suite for that reason alone, and its ABSENCE is
        // already a hard failure in CI's own drift gate — so there is nothing for this test to add there.
        if (string.IsNullOrEmpty(path)) return;

        using var doc = JsonDocument.Parse(File.ReadAllText(path));
        var verbs = new[] { "get", "post", "put", "patch", "delete" };
        int total = 0, withSchema = 0;

        foreach (var pathItem in doc.RootElement.GetProperty("paths").EnumerateObject())
            foreach (var op in pathItem.Value.EnumerateObject())
            {
                if (!verbs.Contains(op.Name)) continue;
                total++;
                if (!op.Value.TryGetProperty("responses", out var responses)) continue;
                var ok = responses.TryGetProperty("200", out var r200) ? r200
                       : responses.TryGetProperty("201", out var r201) ? r201 : default;
                if (ok.ValueKind == JsonValueKind.Object && ok.TryGetProperty("content", out _)) withSchema++;
            }

        Assert.True(withSchema >= Baseline,
            $"Response-schema coverage dropped to {withSchema}/{total} (baseline {Baseline}). " +
            "An endpoint lost its .Produces<T>(), or a new one landed without a response type.");
    }
}
