import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// Generates and uses the device's ES256 identity key for trusted-device auth (AM2/AM4).
///
/// ## Why this is a platform channel and not Dart
///
/// The entire security value of the trusted-device rail is that the private key **cannot leave the
/// device** — that is what makes a stolen refresh token inert (D-081) and a phished code useless.
/// A key generated in Dart lives in the app's heap and its bytes are recoverable from a rooted or
/// jailbroken handset, a memory dump, or a backup. So the key is generated by, and never leaves,
/// the platform keystore:
///
/// * **Android** — `AndroidKeyStore` provider, `EC` / `secp256r1`, `setUserAuthenticationRequired(true)`,
///   and StrongBox (`setIsStrongBoxBacked`) where the hardware offers it.
/// * **iOS** — Secure Enclave (`kSecAttrTokenIDSecureEnclave`) with an access control of
///   `biometryCurrentSet | privateKeyUsage`, so re-enrolling a fingerprint invalidates the key.
///
/// Both platforms gate `sign` behind a biometric prompt, which is what makes "approve this sign-in"
/// an actual user-present assertion rather than a background call any malware could make.
///
/// ## Signature format
///
/// The backend accepts DER (`Rfc3279DerSequence`) or raw r‖s and tries both, so either platform's
/// native output verifies without conversion here.
abstract class DeviceKeyService {
  /// True once a key exists for this install.
  Future<bool> hasKey();

  /// Creates the hardware-backed key pair, returning its base64 SubjectPublicKeyInfo for enrollment.
  /// Calling it again replaces the key — the caller must re-enroll the device afterwards.
  Future<String> createKey();

  /// Base64 SPKI of the existing public key, or null when no key has been created.
  Future<String?> publicKeySpki();

  /// Signs [message] (the challenge nonce) with the private key, prompting for biometrics.
  /// Returns base64 DER. Throws [DeviceKeyException] if the user cancels or auth fails.
  Future<String> sign(String message);

  /// Removes the key material. Called when the device is revoked or the user signs out for good.
  Future<void> deleteKey();
}

class DeviceKeyException implements Exception {
  const DeviceKeyException(this.code, [this.message]);

  /// `user_canceled` | `not_enrolled` | `key_invalidated` | `unavailable` | `unknown`
  final String code;
  final String? message;

  /// True when the key was destroyed by a biometric change — the user must re-enroll the device,
  /// which is a normal lifecycle event and not an error to hide.
  bool get requiresReenrollment => code == 'key_invalidated' || code == 'not_enrolled';

  @override
  String toString() => 'DeviceKeyException($code${message == null ? '' : ': $message'})';
}

/// MethodChannel implementation. The native halves live in
/// `android/app/src/main/kotlin/.../DeviceKeyPlugin.kt` and `ios/Runner/DeviceKeyPlugin.swift`.
class PlatformDeviceKeyService implements DeviceKeyService {
  const PlatformDeviceKeyService([this._channel = const MethodChannel('kurx/device_key')]);

  final MethodChannel _channel;

  @override
  Future<bool> hasKey() => _invoke<bool>('hasKey').then((v) => v ?? false);

  @override
  Future<String> createKey() async {
    final spki = await _invoke<String>('createKey');
    if (spki == null || spki.isEmpty) {
      throw const DeviceKeyException('unknown', 'Key creation returned no public key');
    }
    return spki;
  }

  @override
  Future<String?> publicKeySpki() => _invoke<String>('publicKeySpki');

  @override
  Future<String> sign(String message) async {
    final signature = await _invoke<String>('sign', {'message': message});
    if (signature == null || signature.isEmpty) {
      throw const DeviceKeyException('unknown', 'Signing returned no signature');
    }
    return signature;
  }

  @override
  Future<void> deleteKey() => _invoke<void>('deleteKey');

  /// Platform exceptions are mapped to a typed [DeviceKeyException] so callers branch on a stable
  /// code instead of parsing native error strings that differ per OS.
  Future<T?> _invoke<T>(String method, [Map<String, dynamic>? args]) async {
    try {
      return await _channel.invokeMethod<T>(method, args);
    } on PlatformException catch (e) {
      throw DeviceKeyException(e.code, e.message);
    } on MissingPluginException {
      throw const DeviceKeyException('unavailable', 'Device key plugin is not registered');
    }
  }
}

final deviceKeyServiceProvider =
    Provider<DeviceKeyService>((ref) => const PlatformDeviceKeyService());
